export default new Map<string, string>([
  ["i8", "Int8"],
  ["u8", "UInt8"],
  ["i16", "Int16"],
  ["u16", "UInt16"],
  ["i32", "Int32"],
  ["f32", "Float32"],
  ["u32", "UInt32"],
  ["f64", "Float64"],
  ["i64", "Int64"],
  ["i128", "Int128"],
  ["u128", "UInt128"],
  ["bigint", "BigInt"],
  ["number", "Num"],
  ["Number", "Num"],
  ["string", "String"],
  ["RegExp", "TsRegex"],
  ["void", "Nil"],
  ["undefined", "Nil"],
  ["null", "Nil"],
  ["boolean", "Bool"],
  ["Array", "TsArray"],
  ["Record", "Hash"],
  ["Promise", "MiniFuture"]
])